url: "chirpstack.iut-blagnac.fr"
port: 1883
keepalive: 60
dataFile: "data.csv"
alertFile: "alert.csv"
topics: ["AM107/by-room/+/data"]
selectedData: ["temperature","humidity","co2","activity","tvoc","illumination","infrared","infrared_and_visible","pressure"]
rest_duration  : 30
running_time : 10
thresholds:
  temperature : 24
  humidity : 40
  co2 : 10000
  activity : 300
  tvoc : 500
  illumination : 100
  infrared : 100
  infrared_and_visible : 100
  pressure : 1100


